#pragma once

#define I2C_DRIVER_I2CD2
#define I2C1_SDA_PIN        14
#define I2C1_SCL_PIN        15

#define OLED_DISPLAY_128X128
#define SPLIT_LAYER_STATE_ENABLE
#define SPLIT_LED_STATE_ENABLE
#define SPLIT_MODS_ENABLE
#define SPLIT_OLED_ENABLE


#define SPLIT_TRANSACTION_IDS_USER RPC_ID_LAST_KEY

#define OLED_TIMEOUT        30000
